// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package container

// Injectors from wire.go:

func initEsim() *Esim {
	config := provideConf()
	logger := provideLogger(config)
	prometheus := providePrometheus(config, logger)
	esimTracer := provideTracer()
	string2 := provideAppName(config)
	esim := &Esim{
		prometheus: prometheus,
		Logger:     logger,
		Conf:       config,
		Tracer:     esimTracer,
		AppName:    string2,
	}
	return esim
}

func NewMockEsim() *Esim {
	config := provideMockConf()
	prometheus := provideMockProme(config)
	logger := provideLogger(config)
	esimTracer := provideNoopTracer()
	string2 := provideMockAppName(config)
	esim := &Esim{
		prometheus: prometheus,
		Logger:     logger,
		Conf:       config,
		Tracer:     esimTracer,
		AppName:    string2,
	}
	return esim
}
